libdfp/libdfp

Makefile.in

On debian and Ubuntu, some flags are passed to enable a hardened build.
This done with environment variable. I added LDFAGS for the .so build

Adding support for LDFLAGS passed from env

---

Makefile.in

Makefile misses that and thus make clean and make distclean do not clean everything
properly

Add removing of libdfp-test-ulps.h

---

Makefile.in

The configure script does not honor the value passed through --docdir, because
Makefile.in is missing the substitution variable @docdir@
This commit adds such variable, thus causing --docdir to be honored

Honor value passed through --docdir

---

make-release.sh

Since configure now attempts to automatically detect the cpu,
make-release.sh doesn't need to force a specific CPU while configuring
libdfp.
Signed-off-by: Tulio Magno Quites Machado Filho <tuliom@linux.vnet.ibm.com>

Remove a workaround from make-release.sh

---

Makefile.in

The build system does not check for included files, leaving incremental builds
in broken states.
This commit uses the options MT, MP, MD, and MF from gcc, in order to create
the dependency relations between source and header files.
This commit fixes #36.

Fix incremental builds

---

Makefile.in
base-math/truncdddf.c
base-math/truncddsf.c
base-math/trunctddf.c
base-math/trunctdsf.c
tests/test-cast-to-overflow.c

This commit fixes incorrect conversions between decimal and binary types that
always produce an infinity for obviously overflowing results, without taking
account of the rounding mode (task #31).
Signed-off-by: Rogerio Alves <rcardoso@linux.vnet.ibm.com>

Fix incorrect conversion on overflow.

---

Makefile.in
base-math/truncdddf.c
base-math/truncddsf.c
base-math/trunctddf.c
base-math/trunctdsf.c
tests/test-cast-to-underflow.c

This commit fixes incorrect conversions between decimal and binary types that
always produce an +/-0.0 for obviously overflowing results, without taking
account of the rounding mode (task #32).
Signed-off-by: Rogerio Alves <rcardoso@linux.vnet.ibm.com>

Fix incorrect conversion on underflow.

---

Makefile.in
base-math/truncdddf.c
base-math/trunctddf.c
tests/test-inexact-exception.c

This commit removes a code that force clear a raised inexact exception. Issues
(#33 #34).
Signed-off-by: Rogerio Alves <rcardoso@linux.vnet.ibm.com>

Fix raised inexact exception wrong cleanup.

---

fmt_d32.c
sysdeps/dpd/dpd-private.h

With this patch, we can use -Wall -Werror on GCC 8.

Cleanup files for GCC 8

---

printf_dfp.c

Replace the following references:
- _IO_size_t with size_t;
- _IO_FILE with FILE.
Signed-off-by: Tulio Magno Quites Machado Filho <tuliom@linux.ibm.com>

Adapt the code for glibc 2.28

---

base-math/trunctdsf.c

This commit fixes the two failures on cast-to-overflow test which
converts a Decimal32 to a float (binary 32). The range should be 38
or FLT_MAX_10_EXP not 39.
Signed-off-by: Rogerio Alves <rcardoso@linux.ibm.com>

Fix overflow test failures for flt32 conversion.

---

base-math/truncddsf.c

The range should be 38 or FLT_MAX_10_EXP not 39 to check if the exponent
is out of range on Decimal64 to float (binary 32) conversion.
Signed-off-by: Rogerio Alves <rcardoso@linux.ibm.com>

Fix expoenent range check on Decimal64 to Float conversion

---

configure
configure.ac

This patch adds support for configure flag --with-cpu for the new CPU z15.
Note: z15==arch13, but there exists gcc/binutils versions which do support -march=arch13 but not -march=z15.
Signed-off-by: Stefan Liebler <stli@linux.ibm.com>

S390: Add support for z15/arch13 s390 cpu.

---

Makefile.in
README.developer

Add 2 patches with simple changes:
1. Re-add information removed from PR #87 .
2. Make libdfp friendlier to downstream by using DESTDIR instead of install_root.

Small fixes

---

sysdeps/s390/dfpu/libdfp-test-ulps

Generated with 'make regen-ulps'.
The ulps are now identical to powerpc64.
See commit "soft-dfp, powerpc64: update ulps".
The tests are now clean on s390 64/31bit with hw/sw dfp.

s390: update ulps

---

tests/gen-libdfp-tests.py

Generating the tests with python3 fails due to the following error:
File "tests/gen-libdfp-tests.py", line 281
op.cppchecks.append(cppcheckdict[earg])
^
TabError: inconsistent use of tabs and spaces in indentation
This patch just exchanges the TAB with spaces.
Signed-off-by: Stefan Liebler <stli@linux.ibm.com>

Fix TabError in tests/gen-libdfp-tests.py. #121

---

ieee754r/fabsd32.c

This function just set the MSB to 0.
Tested on x86_64 and ppc64. I ~didn't~ tested it on a big endian machine.
This closes #106

Generic fabs

---

Makefile.in
configure
configure.ac
libdfp.pc.in

As suggested in #123, this file will ease the usage of libdfp by setting a proper include directory for C headers and the expected `__STDC_WANT_DEC_FP__` definition.

Add pkg-config file

---

Makefile.in

If build in a separate build directory, the configure does not create
the libdfp.pc file in top_srcdir, but in top_builddir.
Furthermore, the install command failed as there was no pkgconfig
directory in inst_libdir. Added the -D flag which creates this directory.

Fix pkg-config.

---

sysdeps/s390/dfpu/quantized32.c

Starting with the recent commit 7a02479235285772ad7a24a6e4828f92b6d068e1
the internal quantized functions are makred as hidden.
This just do the same for s390x there is an own implementation.

S390: Mark internal quantized function as hidden.

---

configure
configure.ac

_Float128 requires a less old ppc64le toolchain, and the check
quietly failed to bump the requirements on such machines due to
the mangling of the "machine" variable.
This fixes #130.

configure: fix compiler/glibc check

---

tests/test-bfp-conversions.c

The _Generic usage exposes _Float128 usage on targets which may not
support it.  Make sure it goes away on targets without KFmode or
TFmode == _Float128.

test-bfp-conversions: don't expose _Float128 if not supported

---

Makefile.in
libdecnumber/Makefile.in
libdecnumber/configure
libdecnumber/configure.ac

This is probably bad practice today, but IBM's internal builders do
this.  The libdfp makefile is overwritten by decnumbers during
configure.  Rename the generated makefile.
Likewise, move the generated config.h to a subdir of the builddir
to ensure it doesn't pollute the normal libdfp include paths.
Signed-off-by: Paul E. Murphy <murphyp@linux.vnet.ibm.com>

libdecnumber: fix srcdir==builddir builds

---

tests/gen-libdfp-tests.py
tests/gen-libdfp-ulps.py

The Makefile will explicitly invoke the detected python interpreter,
however these scripts should use python3 if run directly by a
developer.

Use python3 when running bare scripts

---

configure
configure.ac

generate-changelog.sh is deleted when preparing the
release tarball.  Choose a file which always exists
to prevent breaking release tarballs.
Signed-off-by: Paul E. Murphy <murphyp@linux.vnet.ibm.com>

Detect srcdir with a file not removed in the release tarball 

---

Makefile.in

pkg config files are installed with executable rights which shouldn't
be.

Fix .pc permissions

---

.gitignore
Makefile.in

1.0.15 saw a historical amount of churn.  Admittedly, the clean targets could have used more verification.

Cleanup clean targets

---

sysdeps/powerpc/dfpu/fabsd128.c
sysdeps/powerpc/dfpu/fabsd32.c
sysdeps/powerpc/dfpu/fabsd64.c

The inline asm for fabsd128 works only by strict assumption that it
is not inlined and the src and dst registers selected are identical.
When lto is used it will fail to move the lower half of the
decimal128 value causing strange failures if the value is not
computed in place.
Instead use the builtin, it's been available for quite some time
and can generate the extra move as needed.  Similarly, use the
builtins for other types as the generated code is equivalent.
This fixes the non-trivial failures discovered when turning
on lto from Issue #150.

powerpc: use __builtin_fabsdN for fabsdN

---

.travis.yml

According to https://travis-ci.com/plans, travis-CI is "Free for open source".
Thus this implements a small .travis.yml file which adds builds for amd64, ppc64le
and s390x. The latter two also have a version for software dfp.

Enable travis CI for libdfp.

---

.travis.yml

We've just seen an issue happening on gcc-11.
This is a good change to start testing on different GCC versions.
Unfortunately, gcc-11 is not yet available on Ubuntu [1].
[1] https://launchpad.net/ubuntu/+source/gcc-11
Signed-off-by: Tulio Magno Quites Machado Filho <tuliom@linux.ibm.com>

Run tests on gcc-9 and gcc-10

---

.travis.yml

1. Start running the tests on GCC 11.
2. Guarantee the pkgconfig directory is created before we try to install files in it.

Start testing with GCC 11 and a small pkgconfig fix

---

CONTRIBUTING

Allow contributions to be accepted via DCO or FSF copyright assignment.
This greatly reduces the barriers for third-party contributors.
Fixes #167
Signed-off-by: Paul E. Murphy <murphyp@linux.ibm.com>

 Change contribution requirements to DCO or FSF copyright assignment

---

configure
libdecnumber/aclocal.m4
libdecnumber/configure

The previous regeneration used a debian derived autoconf 2.69 which mistakenly added the --runstatedir option.
This was regenerated with the released version of autoconf 2.69 and fedora 36's automake.

Regenerate configury

---

printf-hooks/printf_dfp.c

GCC 14 exposed an alignment bug in libdfp when passing printf arguments through untyped memory on amd64.
Also, fix a minor formatting issue in code adjacent to fix.
Fixes #189

printf-hooks: copy arguments passed through libc carefully

---

sysdeps/soft-dfp/addsd3.c
sysdeps/soft-dfp/divsd3.c
sysdeps/soft-dfp/mulsd3.c
sysdeps/soft-dfp/subsd3.c

add/subtract/multiply/divide must respect the correct rounding mode when using the soft-dfp implementation.
fixes #201

sysdeps/soft-dfp: respect rounding mode for elementary operations

---

stdlib/strtod32.c
tests/test-strtod.c

Parsing 0 is apparently tricky. nan should only be returned if parsing a nan, otherwise it should return 0.
Improve the testing to verify the quantum exponent is correct for more creative strings representing 0. Expanding the table was done with gemini assistance (aka "AI"). It did a mediocre job, but maybe saved some typing.
Likewise, verify the sign of zero results too.
I suspect the quantum exponent for values like 0.0....0eX may not always be correct, but I am also not sure where this might actually matter.
Fixes: #262

stdlib: fix parsing of certain values of 0 in strtodX
